### ISSUE TITLE
Did you get strange deadzone issue?

### ISSUE THREAD

**Issue by IsoaSFlus** [feroxx/android_device_huawei_prague#1]
I'm sorry to disturb you. I'm working on a device tree for my Huawei p10. But it got a strange deadzone issue like following video: https://youtu.be/R1GvYQf3mec
Did you have the same problem？

**Comment by feroxx** [comment]
what is your android version? i think its related to kernel

**Comment by IsoaSFlus** [comment]
Thanks for your reply!
My device tree is on los 16. And I only build and flash systemimage (phone's stock rom in emui 9.0).

**Comment by IsoaSFlus** [comment]
I have already fixed that, thank you!
